### PR TITLE
Fix1

### LINKED ISSUE #33: Voting Issue
Voting issue to be fixed

### PR DESCRIPTION
**Pull request by Peiprjs**

### CODE REVIEW

**Comment by pgamerx** [comment]
What bout #39

**Review by unknown123456789149 — APPROVED** [review]
looks fine

**Comment by pgamerx** [comment]
We either have to merge this or #39, you guys decide

**Comment by Peiprjs** [comment]
#39 seems to be much smaller an update, TBH

**Comment by pgamerxdev** [comment]
You guys decide and merge by today

**Comment by Peiprjs** [comment]
Eeny, meeny, miny moe?

**Pull request closed without merging**
