### PR TITLE
Make the status better | Please Work

### PR DESCRIPTION
**Pull request by pgamerx**
@Peiprjs and @Luckie6313 please review

### CODE REVIEW

**Review by Peiprjs — APPROVED** [review]
Should work

**Comment by Peiprjs** [comment]
There is this little conflict that can be solved really easily by just using the Development version.

**Comment by pgamerx** [comment]
> There is this little conflict that can be solved really easily by just using the Development version.

Which conflict

**Review by Peiprjs — APPROVED** [review]

**Comment by Peiprjs** [comment]
Merge is go

**Comment by pgamerx** [comment]
Ight

**Pull request merged**
