### PR TITLE
Fix the voting bug once and for all

### LINKED ISSUE #33: Voting Issue
Voting issue to be fixed

### PR DESCRIPTION
**Pull request by pgamerx**
Kindly review this and see if this is a good fix for the same!

### CODE REVIEW

**Comment by pgamerx** [comment]
@Peiprjs and @Luckie6313 Please review

**Review by Peiprjs — APPROVED** [review]
Looks like this could work.

**Comment by Peiprjs** [comment]
I say we go with #39, I am not super confident on my approach, the docs were sketchy at best.

**Comment by Peiprjs** [comment]
@PGamerX-Legacy/pgamerx-maintainers?

**Comment by pgamerx** [comment]
Sure

**Comment by pgamerx** [comment]
@Peiprjs merge?

**Comment by Peiprjs** [comment]
Sounds good to me, do you want to do the honours?

**Comment by Peiprjs** [comment]
Here goes nothing

**Pull request merged**
